### ISSUE TITLE
(2) MdisPlugin: implement meta data accessors

### ISSUE THREAD

**Issue by ihumphrey-usgs** [USGS-Astrogeology/camera_model#16]
Block by:
none

Implement the following methods and related member variables in MdisPlugin:

- [ ] getPluginName(): see [CSM TRD Section 5.6](http://gwg.nga.mil/documents/csmwg/documents/CSM_TRD_Appendix_C_API_Version_3.0__15_November_2010.pdf)
- [ ] getManufacturer(): see [CSM TRD Section 5.9.8.3](http://gwg.nga.mil/documents/csmwg/documents/CSM_TRD_Appendix_C_API_Version_3.0__15_November_2010.pdf); consult with @thareUSGS and @jlaura 
- [ ] getReleaseDate(): ISO 8601 yyymmdd
- [ ] getCsmVersion(): CURRENT_CSM_VERSION (csm.h)
- [ ] getNumModels(): Can be 1 for now, eventually 2 for NA c and WAC? 
- [ ] getModelName()
- [ ] getModelFamily()
- [ ] getModelVersion()

**Comment by makaylas** [comment]
Most of these are going to be hard coded for now
