### ISSUE TITLE
EPIC: Create SET.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#51]
* Load the ISD (read and put into ISD object)
* Load the plugin (dlopen call)
* Create a Model using the ISD plugin ()
* Load some data set to get elevation for a line/sample or pass the min/max of the globe or some other elevation. Shoot for a 60 minute solution.
* Make a call () lots of times

See Ian's wiki page

**Comment by jlaura** [comment]
@twilson271828 Can you add the json reading of the ISD into here?

**Comment by MarjorieH** [comment]
https://github.com/MarjorieH/camera_model/tree/Ticket51

Made an set directory under apps

**Comment by MarjorieH** [comment]
Holding off on bullet #4 for now since it requires a DEM.

**Comment by jlaura** [comment]
For the SET - the desired output would be a CSV file that is ground: x, y, z, dn using imageToGround.

- [ ] Read ISD
- [ ] Instantiate the PlugIn / Create the Model
- [ ] Stub - Get elevation from something - hard coded to sphere for now
- [ ] GDAL Read Image array (http://www.gdal.org/gdal_tutorial.html) (optional) - this supplies DN values
- [ ] For each camera x,y call imageToGround; returns X,Y,Z
- [ ] Write out to CSV X,Y,Z,DN

**Comment by ihumphrey-usgs** [comment]
Preliminary CSV is done, but I'll wait until the ISD reading and GDAL reading is merged into the set.
